// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6i3K65HYK8TPUoplZ5nD7JKT1282NEpE',
    appId: '1:511537109733:web:ff4f760668276164e5d20c',
    messagingSenderId: '511537109733',
    projectId: 'ghostwaterbottle',
    authDomain: 'ghostwaterbottle.firebaseapp.com',
    storageBucket: 'ghostwaterbottle.firebasestorage.app',
    measurementId: 'G-TVS6BGZMPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHMUvGlkJ8sInW6Iw2Umx-nOD58DC5-Ng',
    appId: '1:511537109733:android:0027a4ffc6623141e5d20c',
    messagingSenderId: '511537109733',
    projectId: 'ghostwaterbottle',
    storageBucket: 'ghostwaterbottle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmfU6QdnqpaKQ47CDP60Hgpo_ieugCatE',
    appId: '1:511537109733:ios:7485c51b1eefe941e5d20c',
    messagingSenderId: '511537109733',
    projectId: 'ghostwaterbottle',
    storageBucket: 'ghostwaterbottle.firebasestorage.app',
    iosBundleId: 'com.example.ghost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmfU6QdnqpaKQ47CDP60Hgpo_ieugCatE',
    appId: '1:511537109733:ios:7485c51b1eefe941e5d20c',
    messagingSenderId: '511537109733',
    projectId: 'ghostwaterbottle',
    storageBucket: 'ghostwaterbottle.firebasestorage.app',
    iosBundleId: 'com.example.ghost',
  );
}
